### ISSUE TITLE
Should live link actually work?

### ISSUE THREAD

**Issue by mcraiha** [BabylonJS/CYOS#5]
At the beginning of the documentation there is a line that says:
"Live version: http://www.babylonjs.com/cyos/"
but that http://www.babylonjs.com/cyos/ link just leads to **Page Not found** error page.

So should that link to lead somewhere else? Or is there some kind of misconfiguration?

**Comment by deltakosh** [comment]
I'll fix it :)

**Comment by mcraiha** [comment]
Thanks.
